# Use this file as '/etc/asound.conf',
# or only for the current user as '~/.asoundrc'

# Choose -for now- to NOT use my card as "default" playback and capture device
# so that it does not grab the DAC input, but leave that untouched.
# Avoid that any OS or Desktop sound grabs this card.
# The network player app shall explicitly choose this card,
# such as: "aplay -D dacxo"
# If you want to change that, and have the card as default OS audio device,
# change the first "pcm.dacxo {" line below into: "pcm.!default {"
pcm.dacxo {
    type plug   # support translation of 'S24_3LE' (from 'flac') to 'S24_LE'
    slave.pcm "dacxo_hw"
}

# Keep the control alias if you want 'amixer' to find it easily
ctl.dacxo {
    type hw
    card DACXO
}

# The raw hardware definition
pcm.dacxo_hw {
    type hw
    card DACXO
}
