/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.3.0.109 */
/* Module Version: 5.7 */
/* E:\lscc\diamond\3.3_x64\ispfpga\bin\nt64\scuba.exe -w -n Ipexpr_fifo -lang verilog -synth synplify -bus_exp 7 -bb -arch xo2c00 -type ebfifo -depth 4096 -width 9 -rwidth 9 -no_enable -pe 16 -pf 4080  */
/* Sat Jun 13 22:03:55 2015 */


`timescale 1 ns / 1 ps
module Ipexpr_fifo (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, 
    Q, Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [8:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [8:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire scuba_vhi;
    wire Empty_int;
    wire Full_int;
    wire scuba_vlo;

    defparam Ipexpr_fifo_0_4.FULLPOINTER1 = "0b01111111111110" ;
    defparam Ipexpr_fifo_0_4.FULLPOINTER = "0b10000000000000" ;
    defparam Ipexpr_fifo_0_4.AFPOINTER1 = "0b01111111011110" ;
    defparam Ipexpr_fifo_0_4.AFPOINTER = "0b01111111100000" ;
    defparam Ipexpr_fifo_0_4.AEPOINTER1 = "0b00000000100010" ;
    defparam Ipexpr_fifo_0_4.AEPOINTER = "0b00000000100000" ;
    defparam Ipexpr_fifo_0_4.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam Ipexpr_fifo_0_4.GSR = "DISABLED" ;
    defparam Ipexpr_fifo_0_4.RESETMODE = "ASYNC" ;
    defparam Ipexpr_fifo_0_4.REGMODE = "NOREG" ;
    defparam Ipexpr_fifo_0_4.CSDECODE_R = "0b11" ;
    defparam Ipexpr_fifo_0_4.CSDECODE_W = "0b11" ;
    defparam Ipexpr_fifo_0_4.DATA_WIDTH_R = 2 ;
    defparam Ipexpr_fifo_0_4.DATA_WIDTH_W = 2 ;
    FIFO8KB Ipexpr_fifo_0_4 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[0]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[1]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[0]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[0]), .DO1(Q[1]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(Empty_int), .AEF(AlmostEmpty), .AFF(AlmostFull), .FF(Full_int));

    defparam Ipexpr_fifo_1_3.FULLPOINTER1 = "0b00000000000000" ;
    defparam Ipexpr_fifo_1_3.FULLPOINTER = "0b11111111111110" ;
    defparam Ipexpr_fifo_1_3.AFPOINTER1 = "0b00000000000000" ;
    defparam Ipexpr_fifo_1_3.AFPOINTER = "0b11111111111110" ;
    defparam Ipexpr_fifo_1_3.AEPOINTER1 = "0b00000000000000" ;
    defparam Ipexpr_fifo_1_3.AEPOINTER = "0b11111111111110" ;
    defparam Ipexpr_fifo_1_3.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam Ipexpr_fifo_1_3.GSR = "DISABLED" ;
    defparam Ipexpr_fifo_1_3.RESETMODE = "ASYNC" ;
    defparam Ipexpr_fifo_1_3.REGMODE = "NOREG" ;
    defparam Ipexpr_fifo_1_3.CSDECODE_R = "0b11" ;
    defparam Ipexpr_fifo_1_3.CSDECODE_W = "0b11" ;
    defparam Ipexpr_fifo_1_3.DATA_WIDTH_R = 2 ;
    defparam Ipexpr_fifo_1_3.DATA_WIDTH_W = 2 ;
    FIFO8KB Ipexpr_fifo_1_3 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[2]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[3]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[2]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[2]), .DO1(Q[3]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam Ipexpr_fifo_2_2.FULLPOINTER1 = "0b00000000000000" ;
    defparam Ipexpr_fifo_2_2.FULLPOINTER = "0b11111111111110" ;
    defparam Ipexpr_fifo_2_2.AFPOINTER1 = "0b00000000000000" ;
    defparam Ipexpr_fifo_2_2.AFPOINTER = "0b11111111111110" ;
    defparam Ipexpr_fifo_2_2.AEPOINTER1 = "0b00000000000000" ;
    defparam Ipexpr_fifo_2_2.AEPOINTER = "0b11111111111110" ;
    defparam Ipexpr_fifo_2_2.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam Ipexpr_fifo_2_2.GSR = "DISABLED" ;
    defparam Ipexpr_fifo_2_2.RESETMODE = "ASYNC" ;
    defparam Ipexpr_fifo_2_2.REGMODE = "NOREG" ;
    defparam Ipexpr_fifo_2_2.CSDECODE_R = "0b11" ;
    defparam Ipexpr_fifo_2_2.CSDECODE_W = "0b11" ;
    defparam Ipexpr_fifo_2_2.DATA_WIDTH_R = 2 ;
    defparam Ipexpr_fifo_2_2.DATA_WIDTH_W = 2 ;
    FIFO8KB Ipexpr_fifo_2_2 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[4]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[5]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[4]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[4]), .DO1(Q[5]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam Ipexpr_fifo_3_1.FULLPOINTER1 = "0b00000000000000" ;
    defparam Ipexpr_fifo_3_1.FULLPOINTER = "0b11111111111110" ;
    defparam Ipexpr_fifo_3_1.AFPOINTER1 = "0b00000000000000" ;
    defparam Ipexpr_fifo_3_1.AFPOINTER = "0b11111111111110" ;
    defparam Ipexpr_fifo_3_1.AEPOINTER1 = "0b00000000000000" ;
    defparam Ipexpr_fifo_3_1.AEPOINTER = "0b11111111111110" ;
    defparam Ipexpr_fifo_3_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam Ipexpr_fifo_3_1.GSR = "DISABLED" ;
    defparam Ipexpr_fifo_3_1.RESETMODE = "ASYNC" ;
    defparam Ipexpr_fifo_3_1.REGMODE = "NOREG" ;
    defparam Ipexpr_fifo_3_1.CSDECODE_R = "0b11" ;
    defparam Ipexpr_fifo_3_1.CSDECODE_W = "0b11" ;
    defparam Ipexpr_fifo_3_1.DATA_WIDTH_R = 2 ;
    defparam Ipexpr_fifo_3_1.DATA_WIDTH_W = 2 ;
    FIFO8KB Ipexpr_fifo_3_1 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[6]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[7]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[6]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[6]), .DO1(Q[7]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam Ipexpr_fifo_4_0.FULLPOINTER1 = "0b00000000000000" ;
    defparam Ipexpr_fifo_4_0.FULLPOINTER = "0b11111111111110" ;
    defparam Ipexpr_fifo_4_0.AFPOINTER1 = "0b00000000000000" ;
    defparam Ipexpr_fifo_4_0.AFPOINTER = "0b11111111111110" ;
    defparam Ipexpr_fifo_4_0.AEPOINTER1 = "0b00000000000000" ;
    defparam Ipexpr_fifo_4_0.AEPOINTER = "0b11111111111110" ;
    defparam Ipexpr_fifo_4_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam Ipexpr_fifo_4_0.GSR = "DISABLED" ;
    defparam Ipexpr_fifo_4_0.RESETMODE = "ASYNC" ;
    defparam Ipexpr_fifo_4_0.REGMODE = "NOREG" ;
    defparam Ipexpr_fifo_4_0.CSDECODE_R = "0b11" ;
    defparam Ipexpr_fifo_4_0.CSDECODE_W = "0b11" ;
    defparam Ipexpr_fifo_4_0.DATA_WIDTH_R = 2 ;
    defparam Ipexpr_fifo_4_0.DATA_WIDTH_W = 2 ;
    FIFO8KB Ipexpr_fifo_4_0 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[8]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[8]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[8]), .DO1(), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar end

endmodule
